export const airportCodes: Record<string, string> = {
  // Major International Airports
  "new delhi": "DEL",
  "delhi": "DEL",
  "mumbai": "BOM",
  "bengaluru": "BLR",
  "bangalore": "BLR",
  "chennai": "MAA",
  "hyderabad": "HYD",
  "kolkata": "CCU",
  "kochi": "COK",
  "cochin": "COK",
  "thiruvananthapuram": "TRV",
  "trivandrum": "TRV",
  "ahmedabad": "AMD",
  "pune": "PNQ",
  "goa": "GOI",
  "gaya": "GAY",
  "chandigarh": "IXC",
  "amritsar": "ATQ",
  "jaipur": "JAI",
  "lucknow": "LKO",
  "bhubaneswar": "BBI",
  "tiruchirappalli": "TRZ",
  "trichy": "TRZ",
  "madurai": "IXM",
  "mangaluru": "IXE",
  "mangalore": "IXE",
  "kannur": "CNN",
  "varanasi": "VNS",
  "patna": "PAT",
  "raipur": "RPR",
  "bagdogra": "IXB",
  "srinagar": "SXR",
  "jodhpur": "JDH",
  "udaipur": "UDR",
  "dehradun": "DED",
  "guwahati": "GAU",
  "imphal": "IMF",
  "port blair": "IXZ",

  // Domestic / Regional Airports
  "agra": "AGR",
  "aizawl": "AJL",
  "akola": "AKD",
  "vadodara": "BDQ",
  "baroda": "BDQ",
  "bhopal": "BHO",
  "bhavnagar": "BHU",
  "bikaner": "BKB",
  "bathinda": "BUP",
  "kadapa": "CDP",
  "coimbatore": "CJB",
  "darbhanga": "DBR",
  "deoghar": "DGH",
  "dibrugarh": "DIB",
  "diu": "DIU",
  "dimapur": "DMU",
  "gorakhpur": "GOP",
  "hubballi": "HBX",
  "hubli": "HBX",
  "khajuraho": "HJR",
  "indore": "IDR",
  "agartala": "IXA",
  "prayagraj": "IXD",
  "allahabad": "IXD",
  "belagavi": "IXG",
  "belgaum": "IXG",
  "jammu": "IXJ",
  "keshod": "IXK",
  "leh": "IXL",
  "ranchi": "IXR",
  "silchar": "IXS",
  "jabalpur": "JLR",
  "jorhat": "JRH",
  "kanpur": "KNU",
  "kolhapur": "KLH",
  "kishangarh": "KQH",
  "nagpur": "NAG",
  "pantnagar": "PGH",
  "porbandar": "PBD",
  "rajahmundry": "RJA",
  "rajkot": "RAJ",
  "rewa": "REW",
  "rupsi": "RDP",
  "shillong": "SHL",
  "shimla": "SLV",
  "surat": "STV",
  "tezpur": "TEZ",
  "tirupati": "TIR",
  "satna": "TNI",
  "udhna": "UDN",
  "vijayawada": "VGA",
  "visakhapatnam": "VTZ",
  "vizag": "VTZ",

  // Island Airports
  "agatti": "AGX",
};

export function getCityNameFromCode(code: string): string {
  const entry = Object.entries(airportCodes).find(([_, c]) => c === code);
  return entry ? entry[0] : code;
}

export function getAirportCode(cityName: string): string {
  const normalizedCity = cityName.trim().toLowerCase();
  return airportCodes[normalizedCity] || "";
}
